runtime: java
env : flex
inbound_services:
  - warmup
derived_file_type:
  - java_precompiled
resources:
  memory_gb: 4
runtime_config:
  jdk: openjdk8

handlers:
  - url: /.*
    script: this field is required, but ignored
skip_files: app.yaml